# Generated by Django 3.2.25 on 2025-05-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anarana', models.CharField(max_length=50)),
                ('fanampiny', models.CharField(max_length=50)),
                ('daty_nahaterahana', models.DateField()),
                ('lahy_vavy', models.CharField(max_length=4)),
                ('toerana_nahaterahana', models.CharField(max_length=50)),
                ('firenena_onenana', models.CharField(max_length=50)),
                ('faritra', models.IntegerField()),
                ('fivondronana', models.IntegerField()),
                ('firaisana', models.IntegerField()),
                ('adiresy', models.CharField(max_length=50)),
                ('diplaoma', models.CharField(max_length=50)),
                ('asa', models.CharField(max_length=50)),
                ('ray', models.BigIntegerField()),
                ('reny', models.BigIntegerField()),
            ],
        ),
    ]
