# Generated by Django 3.2.25 on 2025-06-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olonas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olona',
            name='fizokiana',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
