# Generated by Django 3.2.25 on 2025-06-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olonas', '0002_olona_fizokiana'),
    ]

    operations = [
        migrations.AddField(
            model_name='olona',
            name='fiantsoana',
            field=models.CharField(default='tsisy', max_length=20),
        ),
    ]
