# Generated by Django 3.2.25 on 2025-06-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olonas', '0004_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faritany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anarana', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faritra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anarana', models.CharField(max_length=50)),
                ('faritany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olonas.faritany')),
            ],
        ),
        migrations.CreateModel(
            name='Fivondronana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anarana', models.CharField(max_length=50)),
                ('Faritra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olonas.faritra')),
            ],
        ),
        migrations.CreateModel(
            name='firaisana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anarana', models.CharField(max_length=50)),
                ('Faritra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olonas.fivondronana')),
            ],
        ),
    ]
