# Generated by Django 3.2.25 on 2025-06-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olonas', '0005_faritany_faritra_firaisana_fivondronana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firaisana',
            old_name='Faritra',
            new_name='fivondronana',
        ),
        migrations.RenameField(
            model_name='fivondronana',
            old_name='Faritra',
            new_name='faritra',
        ),
    ]
