# Generated by Django 5.2.3 on 2025-06-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olonas", "0006_auto_20250628_1457"),
    ]

    operations = [
        
        migrations.AddField(
            model_name="olona",
            name="faritra",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="olonas.faritra",
            ),
        ),
        migrations.AddField(
            model_name="olona",
            name="firaisana",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="olonas.firaisana",
            ),
        ),
        migrations.AddField(
            model_name="olona",
            name="fivondronana",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="olonas.fivondronana",
            ),
        ),
    ]
