# Generated by Django 5.2.4 on 2025-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olonas', '0007_remove_olona_ncommune_remove_olona_ndistrict_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vady',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lahy', models.BigIntegerField()),
                ('id_vavy', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
