# Generated by Django 5.2.4 on 2025-09-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olonas', '0008_vady_delete_city_delete_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olona',
            name='faritra',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='olonas.faritra'),
        ),
        migrations.AlterField(
            model_name='olona',
            name='firaisana',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='olonas.firaisana'),
        ),
        migrations.AlterField(
            model_name='olona',
            name='fivondronana',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='olonas.fivondronana'),
        ),
    ]
